services:
  web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./code:/code
        - ./nginx:/etc/nginx/conf.d
    links:
        - php
  php:
    image: php:8.1-fpm
    volumes:
        - ./code:/code